[package]
name = "csg-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.9"
image = { version = "0.25.9", default-features = false, features = [
  "png",
  "rayon",
] }
rayon = "1.11.0"
